Projects/prj5/django-crud-parent-child-master/apps/apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import theme.views
import books_simple.urls
import books_pc_formset.urls
import books_pc_formset2.urls
import books_pc_multi_view.urls
import books_pc_multi_view2.urls

urlpatterns = [
    url(r'^$', theme.views.home, name='home'),
    url(r'^books_simple/', include(books_simple.urls, namespace='books_simple')),
    url(r'^books_pc_formset/', include(books_pc_formset.urls, namespace='books_pc_formset')),
    url(r'^books_pc_formset2/', include(books_pc_formset2.urls, namespace='books_pc_formset2')),
    url(r'^books_pc_multi_view/', include(books_pc_multi_view.urls, namespace='books_pc_multi_view')),
    url(r'^books_pc_multi_view2/', include(books_pc_multi_view2.urls, namespace='books_pc_multi_view2')),
    url(r'^admin/', include(admin.site.urls)),
]

Projects/prj5/django-crud-parent-child-master/apps/books_pc_formset/urls.py
from django.conf.urls import patterns, url

from books_pc_formset import views

urlpatterns = [
  url(r'^$', views.home, name='home'),
  url(r'^new$', views.book_create, name='book_new'),
  url(r'^edit/(?P<pk>\d+)$', views.book_update, name='book_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.book_delete, name='book_delete'),
]

Projects/prj5/django-crud-parent-child-master/apps/books_pc_formset/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_pc_formset:book_edit', kwargs={'pk': self.pk})


class Tag(models.Model):
    book = models.ForeignKey(Book)
    name = models.CharField(max_length=200)
    weight = models.IntegerField()

    def __unicode__(self):
        return self.name

Projects/prj5/django-crud-parent-child-master/apps/books_pc_formset/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from books_pc_formset.models import Book, Tag

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'pages']

def home(request, template_name='books_pc_formset/home.html'):
    books = Book.objects.all()
    ctx = {}
    ctx['books'] = books
    return render(request, template_name, ctx)

def book_create(request, template_name='books_pc_formset/book_form.html'):
    InlineFormSet = inlineformset_factory(Book, Tag, fields=('name', 'weight'))
    form = BookForm(request.POST or None)
    formset = InlineFormSet(request.POST or None, instance=Book())
    if form.is_valid() and formset.is_valid():
        book = form.save()
        formset.instance = book
        formset.save()
        return redirect('books_pc_formset:home')
    ctx = {}
    ctx['form'] = form
    ctx['formset'] = formset
    return render(request, template_name, ctx)

def book_update(request, pk, template_name='books_pc_formset/book_form.html'):
    InlineFormSet = inlineformset_factory(Book, Tag, fields=('name', 'weight'))
    book = get_object_or_404(Book, pk=pk)
    form = BookForm(request.POST or None, instance=book)
    formset = InlineFormSet(request.POST or None, instance=book)
    if form.is_valid() and formset.is_valid():
        book = form.save()
        formset.instance = book
        formset.save()
        return redirect('books_pc_formset:home')
    ctx = {}
    ctx['form'] = form
    ctx['formset'] = formset
    return render(request, template_name, ctx)

def book_delete(request, pk, template_name='books_pc_formset/book_confirm_delete.html'):
    book = get_object_or_404(Book, pk=pk)
    if request.method=='POST':
        book.delete()
        return redirect('books_pc_formset:home')
    ctx = {}
    ctx['book'] = book
    return render(request, template_name, ctx)

Projects/prj5/django-crud-parent-child-master/apps/books_pc_formset/templates/books_pc_formset/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}
{% include "books_pc_formset/nav.html" with book=book title="Delete" %}

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ book }}" ?
    <input type="submit" value="Submit" />
</form>

{% endblock %}

Projects/prj5/django-crud-parent-child-master/apps/books_pc_formset/templates/books_pc_formset/book_form.html
{% extends "base.html" %}

{% block content %}
{% include "books_pc_formset/nav.html" with book=book title="Edit" %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <strong>Tags<strong>
    <table>
    {{ formset.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>

{% endblock %}

Projects/prj5/django-crud-parent-child-master/apps/books_pc_formset/templates/books_pc_formset/home.html
{% extends "base.html" %}

{% block content %}
{% include "books_pc_formset/nav.html" %}

Books Parent/Child Formset

<ul>
    {% for book in books %}
    <li>{{ book.name }}  ({{ book.pages }} Pages)
    <a href="{% url 'books_pc_formset:book_edit' book.id %}">edit</a>
    <a href="{% url 'books_pc_formset:book_delete' book.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_pc_formset:book_new' %}">New</a>

{% endblock %}

Projects/prj5/django-crud-parent-child-master/apps/books_pc_formset/templates/books_pc_formset/nav.html
<h2>
<a href="{% url 'books_pc_formset:home' %}">Application Home</a>
{% if book %}
&gt; <a href="{% url 'books_pc_formset:book_edit' book.id %}">{{ book }}</a>
{% endif %}
{% if title %}
&gt; {{ title }}
{% endif %}
</h2>