Projects/prj5/django-crud-parent-child-master/apps/apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import theme.views
import books_simple.urls
import books_pc_formset.urls
import books_pc_formset2.urls
import books_pc_multi_view.urls
import books_pc_multi_view2.urls

urlpatterns = [
    url(r'^$', theme.views.home, name='home'),
    url(r'^books_simple/', include(books_simple.urls, namespace='books_simple')),
    url(r'^books_pc_formset/', include(books_pc_formset.urls, namespace='books_pc_formset')),
    url(r'^books_pc_formset2/', include(books_pc_formset2.urls, namespace='books_pc_formset2')),
    url(r'^books_pc_multi_view/', include(books_pc_multi_view.urls, namespace='books_pc_multi_view')),
    url(r'^books_pc_multi_view2/', include(books_pc_multi_view2.urls, namespace='books_pc_multi_view2')),
    url(r'^admin/', include(admin.site.urls)),
]

Projects/prj5/django-crud-parent-child-master/apps/books_pc_multi_view/urls.py
from django.conf.urls import patterns, url

from books_pc_multi_view import views

urlpatterns = [
  url(r'^$', views.home, name='home'),

  url(r'^book_view/(?P<pk>\d+)$', views.book_view, name='book_view'),
  url(r'^book_new$', views.book_create, name='book_new'),
  url(r'^book_edit/(?P<pk>\d+)$', views.book_update, name='book_edit'),
  url(r'^book_delete/(?P<pk>\d+)$', views.book_delete, name='book_delete'),

  url(r'^review_new/(?P<parent_pk>\d+)$', views.review_create, name='review_new'),
  url(r'^review_edit/(?P<pk>\d+)$', views.review_update, name='review_edit'),
  url(r'^review_delete/(?P<pk>\d+)$', views.review_delete, name='review_delete'),
]

Projects/prj5/django-crud-parent-child-master/apps/books_pc_multi_view/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_pc_multi_view:book_edit', kwargs={'pk': self.pk})


class Review(models.Model):
    book = models.ForeignKey(Book)
    name = models.CharField(max_length=200)
    review = models.TextField()

    def __unicode__(self):
        return "Review from: " + self.name

    def get_absolute_url(self):
        return reverse('books_pc_multi_view:review_edit', kwargs={'pk': self.pk})

Projects/prj5/django-crud-parent-child-master/apps/books_pc_multi_view/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from books_pc_multi_view.models import Book, Review

# ========== Forms =========

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'pages']

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['name', 'review']


# ========== Home =========

def home(request, template_name='books_pc_multi_view/home.html'):
    books = Book.objects.all()
    ctx = {}
    ctx['books'] = books
    return render(request, template_name, ctx)
    

# ========== Book CRUD =========

def book_view(request, pk, template_name='books_pc_multi_view/book_view.html'):
    book= get_object_or_404(Book, pk=pk)
    reviews = Review.objects.filter(book=book)
    ctx = {}
    ctx["book"] = book
    ctx["reviews"] = reviews
    return render(request, template_name, ctx)

def book_create(request, template_name='books_pc_multi_view/book_form.html'):
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('books_pc_multi_view:home')
    ctx = {}
    ctx["form"] = form
    return render(request, template_name, ctx)

def book_update(request, pk, template_name='books_pc_multi_view/book_form.html'):
    book= get_object_or_404(Book, pk=pk)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('books_pc_multi_view:home')
    ctx = {}
    ctx["form"] = form
    ctx["book"] = book
    return render(request, template_name, ctx)

def book_delete(request, pk, template_name='books_pc_multi_view/book_confirm_delete.html'):
    book= get_object_or_404(Book, pk=pk)    
    if request.method=='POST':
        book.delete()
        return redirect('books_pc_multi_view:home')
    ctx = {}
    ctx["object"] = book
    ctx["book"] = book
    return render(request, template_name, ctx)


# ========== Review CRUD =========

def review_create(request, parent_pk, template_name='books_pc_multi_view/review_form.html'):
    book = get_object_or_404(Book, pk=parent_pk)
    form = ReviewForm(request.POST or None)
    if form.is_valid():
        review = form.save(commit=False)
        review.book = book
        review.save()
        return redirect('books_pc_multi_view:book_view', parent_pk)
    ctx = {}
    ctx["form"] = form
    ctx["book"] = book
    return render(request, template_name, ctx)

def review_update(request, pk, template_name='books_pc_multi_view/review_form.html'):
    review = get_object_or_404(Review, pk=pk)
    parent_pk = review.book.pk
    form = ReviewForm(request.POST or None, instance=review)
    if form.is_valid():
        form.save()
        return redirect('books_pc_multi_view:book_view', parent_pk)
    ctx = {}
    ctx["form"] = form
    ctx["book"] = review.book
    return render(request, template_name, ctx)

def review_delete(request, pk, template_name='books_pc_multi_view/review_confirm_delete.html'):
    review = get_object_or_404(Review, pk=pk)    
    parent_pk = review.book.pk
    if request.method=='POST':
        review.delete()
        return redirect('books_pc_multi_view:book_view', parent_pk)
    ctx = {}
    ctx["object"] = review
    ctx["book"] = review.book
    return render(request, template_name, ctx)

Projects/prj5/django-crud-parent-child-master/apps/books_pc_multi_view/templates/books_pc_multi_view/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}
{% include "books_pc_multi_view/nav.html" with book=book title="Delete" %}

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

Projects/prj5/django-crud-parent-child-master/apps/books_pc_multi_view/templates/books_pc_multi_view/book_form.html
{% extends "base.html" %}


{% block content %}
{% include "books_pc_multi_view/nav.html" with book=book title="Edit" %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

Projects/prj5/django-crud-parent-child-master/apps/books_pc_multi_view/templates/books_pc_multi_view/book_view.html
{% extends "base.html" %}


{% block content %}
{% include "books_pc_multi_view/nav.html" with book=book title="View" %}

Pages: {{ book.pages }}

<h2>Reviews</h2>
<ul>
    {% for review in reviews %}
    <li>
        {{ review.name }}<br>
        {{ review.review|linebreaks }}
        <br>
        <a href="{% url 'books_pc_multi_view:review_edit' review.id %}">edit</a>
        <a href="{% url 'books_pc_multi_view:review_delete' review.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_pc_multi_view:review_new' book.id %}">New Review</a>
{% endblock %}

Projects/prj5/django-crud-parent-child-master/apps/books_pc_multi_view/templates/books_pc_multi_view/home.html
{% extends "base.html" %}

{% block title %}Book List{% endblock %}

{% block content %}
{% include "books_pc_multi_view/nav.html" %}

Books Parent/Child with Multi View

<ul>
    {% for book in books %}
    <li>{{ book.name }}  ({{ book.pages }} Pages)
    <a href="{% url 'books_pc_multi_view:book_view' book.id %}">view</a>
    <a href="{% url 'books_pc_multi_view:book_edit' book.id %}">edit</a>
    <a href="{% url 'books_pc_multi_view:book_delete' book.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_pc_multi_view:book_new' %}">New</a>
{% endblock %}

Projects/prj5/django-crud-parent-child-master/apps/books_pc_multi_view/templates/books_pc_multi_view/nav.html
<h2>
<a href="{% url 'books_pc_multi_view:home' %}">Application Home</a>
{% if book %}
&gt; <a href="{% url 'books_pc_multi_view:book_view' book.id %}">{{ book.name }}</a>
{% endif %}
{% if title %}
&gt; {{ title }}
{% endif %}
</h2>

Projects/prj5/django-crud-parent-child-master/apps/books_pc_multi_view/templates/books_pc_multi_view/review_confirm_delete.html
{% extends "base.html" %}


{% block content %}
{% include "books_pc_multi_view/nav.html" with book=book title="Delete Review" %}
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

Projects/prj5/django-crud-parent-child-master/apps/books_pc_multi_view/templates/books_pc_multi_view/review_form.html
{% extends "base.html" %}


{% block content %}
{% include "books_pc_multi_view/nav.html" with book=book title="Edit Review" %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}