Projects/prj5/django-crud-parent-child-master/apps/apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import theme.views
import books_simple.urls
import books_pc_formset.urls
import books_pc_formset2.urls
import books_pc_multi_view.urls
import books_pc_multi_view2.urls

urlpatterns = [
    url(r'^$', theme.views.home, name='home'),
    url(r'^books_simple/', include(books_simple.urls, namespace='books_simple')),
    url(r'^books_pc_formset/', include(books_pc_formset.urls, namespace='books_pc_formset')),
    url(r'^books_pc_formset2/', include(books_pc_formset2.urls, namespace='books_pc_formset2')),
    url(r'^books_pc_multi_view/', include(books_pc_multi_view.urls, namespace='books_pc_multi_view')),
    url(r'^books_pc_multi_view2/', include(books_pc_multi_view2.urls, namespace='books_pc_multi_view2')),
    url(r'^admin/', include(admin.site.urls)),
]

Projects/prj5/django-crud-parent-child-master/apps/books_pc_formset2/urls.py
from django.conf.urls import patterns, url

from books_pc_formset2 import views

urlpatterns = [
  url(r'^$', views.home, name='home'),

  url(r'^person_new$', views.person_create, name='person_new'),
  url(r'^person_edit/(?P<pk>\d+)$', views.person_update, name='person_edit'),
  url(r'^person_delete/(?P<pk>\d+)$', views.person_delete, name='person_delete'),

  url(r'^book_new$', views.book_create, name='book_new'),
  url(r'^book_edit/(?P<pk>\d+)$', views.book_update, name='book_edit'),
  url(r'^book_delete/(?P<pk>\d+)$', views.book_delete, name='book_delete'),
]

Projects/prj5/django-crud-parent-child-master/apps/books_pc_formset2/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Person(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_pc_formset2:person_edit', kwargs={'pk': self.pk})


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_pc_formset2:book_edit', kwargs={'pk': self.pk})


class Contributor(models.Model):
    AUTHOR = 1
    EDITOR = 2
    REVIEWER = 3
    CONTRIBUTION_CHOICES = (
        (AUTHOR, "Author"),
        (EDITOR, "EDITOR"),
        (REVIEWER, "REVIEWER"),
    )
    book = models.ForeignKey(Book)
    person = models.ForeignKey(Person)
    contribution = models.IntegerField(choices=CONTRIBUTION_CHOICES)

    def __unicode__(self):
        return "%s %s" % (self.contribution, self.person)

Projects/prj5/django-crud-parent-child-master/apps/books_pc_formset2/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from books_pc_formset2.models import Book, Contributor, Person

# ============ Forms ===============

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'pages']

class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = ['name', 'email']

# ============ Home ===============

def home(request, template_name='books_pc_formset2/home.html'):
    books = Book.objects.all()
    persons = Person.objects.all()
    ctx = {}
    ctx['books'] = books
    ctx['persons'] = persons
    return render(request, template_name, ctx)


# ============ Book CRUD ===============

def book_create(request, template_name='books_pc_formset2/book_form.html'):
    InlineFormSet = inlineformset_factory(Book, Contributor, fields=('person', 'contribution'))
    form = BookForm(request.POST or None)
    formset = InlineFormSet(request.POST or None, instance=Book())
    if form.is_valid() and formset.is_valid():
        book = form.save()
        formset.instance = book
        formset.save()
        return redirect('books_pc_formset2:home')
    ctx = {}
    ctx["form"] = form
    ctx["formset"] = formset
    return render(request, template_name, ctx)

def book_update(request, pk, template_name='books_pc_formset2/book_form.html'):
    InlineFormSet = inlineformset_factory(Book, Contributor, fields=('person', 'contribution'))
    book= get_object_or_404(Book, pk=pk)
    form = BookForm(request.POST or None, instance=book)
    formset = InlineFormSet(request.POST or None, instance=book)
    if form.is_valid() and formset.is_valid():
        book = form.save()
        formset.instance = book
        formset.save()
        return redirect('books_pc_formset2:home')
    ctx = {}
    ctx["form"] = form
    ctx["formset"] = formset
    return render(request, template_name, ctx)

def book_delete(request, pk, template_name='books_pc_formset2/book_confirm_delete.html'):
    book= get_object_or_404(Book, pk=pk)
    if request.method=='POST':
        book.delete()
        return redirect('books_pc_formset2:home')
    ctx = {}
    ctx["book"] = book
    return render(request, template_name, ctx)


# ============ Person CRUD ===============

def person_create(request, template_name='books_pc_formset2/person_form.html'):
    form = PersonForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('books_pc_formset2:home')
    ctx = {}
    ctx["form"] = form
    return render(request, template_name, ctx)

def person_update(request, pk, template_name='books_pc_formset2/person_form.html'):
    person = get_object_or_404(Person, pk=pk)
    form = PersonForm(request.POST or None, instance=person)
    if form.is_valid():
        form.save()
        return redirect('books_pc_formset2:home')
    ctx = {}
    ctx["form"] = form
    return render(request, template_name, ctx)

def person_delete(request, pk, template_name='books_pc_formset2/person_confirm_delete.html'):
    person= get_object_or_404(Person, pk=pk)
    if request.method=='POST':
        person.delete()
        return redirect('books_pc_formset2:home')
    ctx = {}
    ctx["person"] = person
    return render(request, template_name, ctx)

Projects/prj5/django-crud-parent-child-master/apps/books_pc_formset2/templates/books_pc_formset2/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}
{% include "books_pc_formset2/nav.html" with book=book title="Delete" %}

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ book }}" ?
    <input type="submit" value="Submit" />
</form>

{% endblock %}

Projects/prj5/django-crud-parent-child-master/apps/books_pc_formset2/templates/books_pc_formset2/book_form.html
{% extends "base.html" %}

{% block content %}
{% include "books_pc_formset2/nav.html" with book=book title="Edit Book" %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <strong>Contributors<strong>
    <table>
    {{ formset.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>

{% endblock %}

Projects/prj5/django-crud-parent-child-master/apps/books_pc_formset2/templates/books_pc_formset2/home.html
{% extends "base.html" %}

{% block content %}
{% include "books_pc_formset2/nav.html" %}

<h1>Books Parent/Child Formset2</h1>


<h2>People</h2>
<ul>
    {% for person in persons %}
    <li>{{ person.name }}  ({{ person.email }})
    <a href="{% url 'books_pc_formset2:person_edit' person.id %}">edit</a>
    <a href="{% url 'books_pc_formset2:person_delete' person.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_pc_formset2:person_new' %}">New</a>


<h2>Books</h2>
<ul>
    {% for book in books %}
    <li>{{ book.name }}  ({{ book.pages }} Pages)
    <a href="{% url 'books_pc_formset2:book_edit' book.id %}">edit</a>
    <a href="{% url 'books_pc_formset2:book_delete' book.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_pc_formset2:book_new' %}">New</a>

{% endblock %}

Projects/prj5/django-crud-parent-child-master/apps/books_pc_formset2/templates/books_pc_formset2/nav.html
<h2>
<a href="{% url 'books_pc_formset2:home' %}">Application Home</a>
{% if book %}
&gt; <a href="{% url 'books_pc_formset2:book_edit' book.id %}">{{ book }}</a>
{% endif %}
{% if title %}
&gt; {{ title }}
{% endif %}
</h2>

Projects/prj5/django-crud-parent-child-master/apps/books_pc_formset2/templates/books_pc_formset2/person_confirm_delete.html
{% extends "base.html" %}

{% block content %}
{% include "books_pc_formset2/nav.html" with person=person title="Delete" %}

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ person }}" ?
    <input type="submit" value="Submit" />
</form>

{% endblock %}

Projects/prj5/django-crud-parent-child-master/apps/books_pc_formset2/templates/books_pc_formset2/person_form.html
{% extends "base.html" %}

{% block content %}
{% include "books_pc_formset2/nav.html" with person=person title="Edit Person" %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}